name: Create WeakAuras atlas list update pull request

on:
  schedule:
    - cron:  '55 0 * * *'
  push:
    branches:
      - test
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  AtlasUpdate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create updated atlas list
        shell: pwsh
        run: |
          cd .github/scripts/
          ./UpdateAtlasList.ps1
